// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KLM.Repository.Models;

public partial class AccountTbl
{
    public string AccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public DateOnly DateOfCreation { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AnswerTbl> AnswerTbls { get; set; } = new List<AnswerTbl>();

    public virtual ICollection<OrderTbl> OrderTbls { get; set; } = new List<OrderTbl>();

    public virtual ICollection<QuestionTbl> QuestionTbls { get; set; } = new List<QuestionTbl>();
}