// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KLM.Repository.Models;

public partial class LabTbl
{
    public string LabId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Document { get; set; }

    public DateOnly DateOfCreation { get; set; }

    public DateTime? DateOfDeletion { get; set; }

    public string Status { get; set; }

    public DateOnly? DateOfChangeLab { get; set; }

    public virtual ICollection<ProductKitTbl> Kits { get; set; } = new List<ProductKitTbl>();

    public virtual ICollection<LtypeTbl> Ltypes { get; set; } = new List<LtypeTbl>();
}