// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace KLM.Repository.Models;

public partial class OrderTbl
{
    public string OrderId { get; set; }

    public string AccountId { get; set; }

    public string Note { get; set; }

    public decimal Price { get; set; }

    public string Address { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? ReceiveDate { get; set; }

    public string Status { get; set; }

    public virtual AccountTbl Account { get; set; }

    public virtual ICollection<AvailableLabTbl> AvailableLabTbls { get; set; } = new List<AvailableLabTbl>();

    public virtual ICollection<OrderDetailTbl> OrderDetailTbls { get; set; } = new List<OrderDetailTbl>();
}